# Generated by Django 5.0.4 on 2024-04-10 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_delete_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
