# Generated by Django 5.0.4 on 2024-04-10 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='audio',
            field=models.FileField(default='', upload_to='uploads/channels/episodes/audio/'),
            preserve_default=False,
        ),
    ]
