# Generated by Django 5.0.4 on 2024-04-10 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_episode_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='audio',
            field=models.FileField(upload_to='uploads/episodes/audio/'),
        ),
    ]
