# Generated by Django 5.0.4 on 2024-04-10 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_alter_episode_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='cover',
            field=models.ImageField(blank=True, upload_to='uploads/episodes/cover/'),
        ),
    ]
