# Generated by Django 5.0.4 on 2024-04-10 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activites', '0005_commentlike_episodelike_delete_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlistitem',
            old_name='play_list',
            new_name='playlist',
        ),
    ]
