# Generated by Django 5.0.4 on 2024-04-09 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seenchannels',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='seenepisodes',
            name='customer',
        ),
        migrations.AddField(
            model_name='seenchannels',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_seens', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seenepisodes',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_watched', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
